// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/access-pending" | "/admin" | "/admin/users" | "/ask" | "/development" | "/login" | "/other-teams" | "/projects" | "/projects/[id]" | "/recover" | "/sme-collaboration" | "/tasks" | "/tasks/[id]" | "/team" | "/time-entries" | "/update-password"
type AppRouteHandlerRoutes = "/api/admin/custom-fields" | "/api/admin/reporting-groups" | "/api/admin/reporting-groups/[id]" | "/api/admin/reporting-settings" | "/api/admin/wrike/custom-field-diagnostics" | "/api/admin/wrike/custom-field-mappings" | "/api/admin/wrike/repair-verticals" | "/api/admin/wrike/status-classifications" | "/api/ask" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/microsoft" | "/api/auth/recover" | "/api/auth/update-password" | "/api/conversations" | "/api/conversations/[id]" | "/api/cron/reporting-cleanup" | "/api/cron/wrike-sync" | "/api/wrike/callback" | "/api/wrike/connect" | "/api/wrike/disconnect" | "/api/wrike/health" | "/api/wrike/import-all" | "/api/wrike/import-folder-tasks" | "/api/wrike/import-space" | "/api/wrike/preview" | "/api/wrike/scopes" | "/api/wrike/sources" | "/api/wrike/sync" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/access-pending": {}
  "/admin": {}
  "/admin/users": {}
  "/api/admin/custom-fields": {}
  "/api/admin/reporting-groups": {}
  "/api/admin/reporting-groups/[id]": { "id": string; }
  "/api/admin/reporting-settings": {}
  "/api/admin/wrike/custom-field-diagnostics": {}
  "/api/admin/wrike/custom-field-mappings": {}
  "/api/admin/wrike/repair-verticals": {}
  "/api/admin/wrike/status-classifications": {}
  "/api/ask": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/microsoft": {}
  "/api/auth/recover": {}
  "/api/auth/update-password": {}
  "/api/conversations": {}
  "/api/conversations/[id]": { "id": string; }
  "/api/cron/reporting-cleanup": {}
  "/api/cron/wrike-sync": {}
  "/api/wrike/callback": {}
  "/api/wrike/connect": {}
  "/api/wrike/disconnect": {}
  "/api/wrike/health": {}
  "/api/wrike/import-all": {}
  "/api/wrike/import-folder-tasks": {}
  "/api/wrike/import-space": {}
  "/api/wrike/preview": {}
  "/api/wrike/scopes": {}
  "/api/wrike/sources": {}
  "/api/wrike/sync": {}
  "/ask": {}
  "/auth/callback": {}
  "/development": {}
  "/login": {}
  "/other-teams": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/recover": {}
  "/sme-collaboration": {}
  "/tasks": {}
  "/tasks/[id]": { "id": string; }
  "/team": {}
  "/time-entries": {}
  "/update-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
