// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/access-pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access-pending">> = Specific
  const handler = {} as typeof import("../../app/access-pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ask/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ask">> = Specific
  const handler = {} as typeof import("../../app/ask/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/development">> = Specific
  const handler = {} as typeof import("../../app/development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/other-teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/other-teams">> = Specific
  const handler = {} as typeof import("../../app/other-teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recover">> = Specific
  const handler = {} as typeof import("../../app/recover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sme-collaboration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sme-collaboration">> = Specific
  const handler = {} as typeof import("../../app/sme-collaboration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tasks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../app/tasks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/time-entries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/time-entries">> = Specific
  const handler = {} as typeof import("../../app/time-entries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/update-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/update-password">> = Specific
  const handler = {} as typeof import("../../app/update-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/custom-fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/custom-fields">> = Specific
  const handler = {} as typeof import("../../app/api/admin/custom-fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reporting-groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reporting-groups/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reporting-groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reporting-groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reporting-groups">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reporting-groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reporting-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reporting-settings">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reporting-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/wrike/custom-field-diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wrike/custom-field-diagnostics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/wrike/custom-field-diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/wrike/custom-field-mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wrike/custom-field-mappings">> = Specific
  const handler = {} as typeof import("../../app/api/admin/wrike/custom-field-mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/wrike/repair-verticals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wrike/repair-verticals">> = Specific
  const handler = {} as typeof import("../../app/api/admin/wrike/repair-verticals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/wrike/status-classifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wrike/status-classifications">> = Specific
  const handler = {} as typeof import("../../app/api/admin/wrike/status-classifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ask">> = Specific
  const handler = {} as typeof import("../../app/api/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/microsoft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/microsoft">> = Specific
  const handler = {} as typeof import("../../app/api/auth/microsoft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/recover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/recover">> = Specific
  const handler = {} as typeof import("../../app/api/auth/recover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/update-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/update-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/update-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/reporting-cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/reporting-cleanup">> = Specific
  const handler = {} as typeof import("../../app/api/cron/reporting-cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/wrike-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/wrike-sync">> = Specific
  const handler = {} as typeof import("../../app/api/cron/wrike-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/callback">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/connect">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/disconnect">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/health">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/import-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/import-all">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/import-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/import-folder-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/import-folder-tasks">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/import-folder-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/import-space/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/import-space">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/import-space/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/preview">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/scopes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/scopes">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/scopes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/sources">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wrike/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wrike/sync">> = Specific
  const handler = {} as typeof import("../../app/api/wrike/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
