begin;
select plan(16);
select has_table('public','survey_submissions','survey submissions exist');
select has_table('public','course_development_debrief_responses','debrief responses exist');
select has_table('public','id_sme_review_responses','ID review responses exist');
select has_table('public','survey_attachments','survey attachments exist');
select has_table('public','survey_revisions','survey revisions exist');
select has_table('public','survey_audit_log','survey audit exists');
select has_column('public','wrike_tasks','original_due_date','original due date is retained');
select has_index('public','survey_submissions','survey_debrief_identity_idx','debrief duplicate safeguard exists');
select has_index('public','survey_submissions','survey_id_review_identity_idx','ID review duplicate safeguard exists');
select has_function('public','survey_context_for_task',array['uuid','text'],'trusted context resolver exists');
select has_function('public','survey_create_or_resume',array['uuid','text','uuid'],'create/resume RPC exists');
select has_function('public','survey_save',array['uuid','jsonb','boolean'],'save/submit RPC exists');
select has_function('public','survey_unlock',array['uuid','text','uuid'],'unlock RPC exists');
select has_function('public','survey_relock',array['uuid'],'relock RPC exists');
select ok((select not public from storage.buckets where id='survey-invoices'),'invoice bucket is private');
select is((select file_size_limit from storage.buckets where id='survey-invoices'),10485760::bigint,'invoice limit is 10 MB');
select * from finish();
rollback;
