begin;
select plan(49);
select has_table('public','survey_submissions','survey submissions exist');
select has_table('public','course_development_debrief_responses','debrief responses exist');
select has_table('public','id_sme_review_responses','ID review responses exist');
select has_table('public','survey_attachments','survey attachments exist');
select has_table('public','survey_revisions','survey revisions exist');
select has_table('public','survey_audit_log','survey audit exists');
select has_column('public','wrike_tasks','original_due_date','original due date is retained');
select has_index('public','survey_submissions','survey_debrief_identity_idx','debrief duplicate safeguard exists');
select has_index('public','survey_submissions','survey_id_review_identity_idx','ID review duplicate safeguard exists');
select has_function('public','survey_context_for_task',array['uuid','text'],'trusted context resolver exists');
select has_function('public','survey_create_or_resume',array['uuid','text','uuid'],'create/resume RPC exists');
select has_function('public','survey_create_or_resume',array['uuid','text','uuid','uuid'],'Wrike-subject create/resume RPC exists');
select has_function('public','survey_save',array['uuid','jsonb','boolean'],'save/submit RPC exists');
select has_function('public','survey_unlock',array['uuid','text','uuid'],'unlock RPC exists');
select has_function('public','survey_relock',array['uuid'],'relock RPC exists');
select ok((select not public from storage.buckets where id='survey-invoices'),'invoice bucket is private');
select is((select file_size_limit from storage.buckets where id='survey-invoices'),10485760::bigint,'invoice limit is 10 MB');
select has_function('public','reporting_sme_dashboard_identities',array[]::text[],'SME identity list RPC exists');
select has_function('public','reporting_sme_dashboard_rows',array['uuid'],'SME row RPC exists');
select has_function('public','reporting_current_id_identity',array[]::text[],'current ID mapping RPC exists');
select has_function('public','reporting_id_dashboard_identities',array[]::text[],'admin ID identity RPC exists');
select has_function('public','reporting_id_dashboard_rows',array['uuid'],'ID row RPC exists');
select has_function('public','reporting_id_dashboard_analytics',array['uuid'],'ID analytics RPC exists');
select has_function('public','normalize_course_development_person_name',array['text'],'canonical assignment-name normalizer exists');
select has_function('public','course_development_person_tokens',array['text[]'],'safe multi-person assignment tokenizer exists');
select has_function('public','survey_browse',array['jsonb','integer','integer'],'caller-aware survey browse RPC exists');
select has_function('public','set_application_user_wrike_identity',array['uuid','uuid','uuid','uuid'],'general identity mapping RPC exists');
select has_table('public','project_finalized_course_drafts','finalized course draft storage exists');
select has_table('public','project_finalized_course_draft_audit','finalized course draft audit exists');
select has_function('public','is_safe_finalized_course_draft_url',array['text'],'finalized URL validator exists');
select has_function('public','save_project_finalized_course_draft',array['uuid','text'],'assigned ID save RPC exists');
select has_function('public','remove_project_finalized_course_draft',array['uuid'],'assigned ID remove RPC exists');
select has_function('public','assigned_id_project_controls',array['uuid'],'assigned ID project controls exist');
select has_function('public','sme_project_detail',array['uuid'],'restricted SME project detail exists');
select has_table('public','survey_templates','survey templates exist');
select has_table('public','survey_template_drafts','survey template drafts exist');
select has_table('public','survey_template_versions','immutable survey versions exist');
select has_table('public','survey_template_audit_log','template audit log exists');
select has_column('public','survey_submissions','survey_version_id','submissions pin a survey version');
select has_column('public','survey_submissions','survey_version_number','submissions expose their pinned version number');
select has_column('public','survey_submissions','definition_snapshot','submissions retain a definition snapshot');
select has_column('public','survey_submissions','answers','submissions use generic answers');
select has_column('public','survey_revisions','definition_snapshot','revisions retain definition snapshots');
select has_column('public','survey_revisions','answers_snapshot','revisions retain normalized answer snapshots');
select has_column('public','survey_attachments','question_id','attachments bind to stable question ids');
select has_function('public','survey_admin_templates',array[]::text[],'admin template browser exists');
select has_function('public','survey_personal_requirements',array[]::text[],'personal assignment list exists');
select has_function('public','survey_personal_create_or_resume',array['uuid','uuid'],'assignment-bound personal start exists');
select has_function('public','survey_save_versioned',array['uuid','jsonb','boolean'],'version-aware save exists');
select * from finish();
rollback;
