import { AppShell } from "@/components/app-shell";
import { AdminPanel } from "@/components/admin-panel";
import { requireAdmin } from "@/lib/auth";
import { SELECTED_WRIKE_FOLDERS } from "@/lib/wrike/selected-folders";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ connected?: string; error?: string }> }) {
  const { supabase, profile } = await requireAdmin();
  const params = await searchParams;
  const [{ data: connection }, { data: folderRuns }, { data: unresolvedReferences }, { data: normalizedFields }, { data: workflowStatuses }, { data: manualMappings }, verticalDiagnostics, { data: repairRuns }, identityReviewResult] = await Promise.all([
    supabase.from("wrike_connections").select("status,account_name,api_host,oauth_scopes,token_expires_at,updated_at").eq("organization_id", profile.organization_id).maybeSingle(),
    supabase.from("wrike_folder_task_import_runs").select("id,status,folder_counts,timelog_folder_counts,task_count,unique_timelog_count,task_request_count,timelog_request_count,failed_folder_request_count,folder_failures,duration_ms,folder_definition_count,custom_field_definition_count,metadata_diagnostics,timelog_descendant_strategy,timelog_descendant_diagnostics,reference_data_diagnostics,reference_warning_count,custom_field_conflict_count,custom_field_normalization_diagnostics,task_custom_field_diagnostics,unresolved_reference_count,reference_resolution_diagnostics,error_summary,created_at").eq("organization_id", profile.organization_id).order("created_at", { ascending: false }).limit(10),
    supabase.from("wrike_unresolved_references").select("id,reference_type,wrike_id,sample_values,related_records,occurrence_count,resolution_attempts,first_encountered_at,last_encountered_at,last_attempted_at,last_error,resolution_status").eq("organization_id", profile.organization_id).eq("resolution_status", "unresolved").order("last_encountered_at", { ascending: false }),
    supabase.from("wrike_normalized_custom_fields").select("id,title,normalized_key").eq("organization_id", profile.organization_id).order("title"),
    supabase.from("wrike_workflow_statuses").select("wrike_id,title,status_group,color,dashboard_classification,classification_source,workflow_id").eq("organization_id", profile.organization_id).eq("workflow_id", "IEACHQK7K4BHMLHM").order("display_order"),
    supabase.from("wrike_manual_mappings").select("id,wrike_id,action,target_normalized_field_id,manual_label,reprocess_status,reprocess_error,updated_at").eq("organization_id", profile.organization_id).eq("reference_type", "custom_field").order("updated_at", { ascending: false }),
    supabase.rpc("reporting_vertical_data_quality"),
    supabase.from("wrike_vertical_repair_runs").select("id,status,examined_count,repaired_count,unchanged_count,retained_count,still_incomplete_count,started_at,completed_at,error_summary").eq("organization_id", profile.organization_id).order("started_at", { ascending: false }).limit(10),
    supabase.from("wrike_person_identities").select("id,display_name,email,verification_status,verification_source,candidate_contacts,verification_attempt_count,last_verification_attempt_at,next_verification_attempt_at,last_error").eq("organization_id", profile.organization_id).in("verification_status", ["ambiguous", "not_found", "failed", "unverified"]).order("updated_at", { ascending: false })
  ]);
  return <AppShell isAdmin><header className="page-header"><div><p className="eyebrow">ADMINISTRATIVE FUNCTIONS</p><h1>Data</h1><p>Manage synchronized Wrike data, unresolved references, custom-field mappings, and Online Learning status classifications.</p></div></header>{params.connected && <p className="notice">Wrike connected successfully. The import has not run until you select the button below.</p>}{params.error && <p className="notice error">{params.error}</p>}<AdminPanel connection={connection} folderRuns={(folderRuns ?? []) as never} folders={[...SELECTED_WRIKE_FOLDERS]} unresolvedReferences={(unresolvedReferences ?? []) as never} identityReview={!identityReviewResult.error ? (identityReviewResult.data ?? []) as never : []} normalizedFields={(normalizedFields ?? []) as never} workflowStatuses={(workflowStatuses ?? []) as never} manualMappings={(manualMappings ?? []) as never} verticalDiagnostics={(verticalDiagnostics.data ?? null) as never} verticalDiagnosticsError={verticalDiagnostics.error?.message ?? null} repairRuns={(repairRuns ?? []) as never} /></AppShell>;
}
