"use client";
import { useState } from "react";

type Scope = { id: string; label: string; scope_type: string; source_ids: string[]; is_active: boolean };
export function AdminPanel({ connection, scopes, runs }: { connection: { status: string; account_name: string | null; updated_at: string } | null; scopes: Scope[]; runs: { id: string; status: string; started_at: string; record_counts: Record<string, number>; error_summary: string | null }[] }) {
  const [label, setLabel] = useState(""); const [scopeType, setScopeType] = useState("folder"); const [sourceId, setSourceId] = useState(""); const [message, setMessage] = useState(""); const [preview, setPreview] = useState<{ title: string; status: string }[]>([]); const connected = connection?.status === "connected";
  async function previewScope() { setMessage(""); const response = await fetch("/api/wrike/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scopeType, sourceIds: [sourceId] }) }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error); setPreview(payload.tasks); }
  async function saveScope() { const response = await fetch("/api/wrike/scopes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, scopeType, sourceIds: [sourceId] }) }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error); setMessage("Scope saved. Refresh this page to see it in the list."); }
  async function sync(scopeId: string) { setMessage("Sync is running; this can take a few minutes for a large scope."); const response = await fetch("/api/wrike/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scopeId }) }); const payload = await response.json(); setMessage(response.ok ? `Sync completed: ${payload.tasks} tasks and ${payload.timeEntries} time entries processed.` : payload.error); }
  return <div className="admin-grid"><section className="card"><h2>Wrike connection</h2>{connected ? <><p>Connected to <strong>{connection?.account_name ?? "Wrike"}</strong>.</p><p className="muted">Token last updated {new Date(connection!.updated_at).toLocaleString()}.</p><button className="secondary" onClick={async () => { await fetch("/api/wrike/disconnect", { method: "POST" }); location.reload(); }}>Disconnect</button></> : <><p>Connect an administrator’s Wrike account to browse sources and synchronize reporting data.</p><a className="button" href="/api/wrike/connect">Connect Wrike</a></>}</section><section className="card"><h2>Create tracked scope</h2>{!connected ? <p>Connect Wrike first.</p> : <><div className="form-grid"><input placeholder="Scope label (e.g. Course production)" value={label} onChange={(event) => setLabel(event.target.value)} /><select value={scopeType} onChange={(event) => setScopeType(event.target.value)}><option value="account">Account</option><option value="space">Space</option><option value="folder">Folder</option><option value="project">Project</option><option value="task">Parent task</option><option value="list">List of task IDs</option></select><input placeholder="Wrike source ID" value={sourceId} onChange={(event) => setSourceId(event.target.value)} /></div><div className="filter-bar"><button className="secondary" onClick={previewScope} disabled={!sourceId}>Preview tasks</button><button onClick={saveScope} disabled={!label || !sourceId}>Save scope</button></div>{preview.length > 0 && <p className="muted">Preview: {preview.slice(0, 3).map((task) => task.title).join(", ")}{preview.length > 3 ? "…" : ""}</p>}</>}</section>{message && <p className={message.includes("completed") || message.includes("saved") ? "notice" : "notice error"}>{message}</p>}<section className="card"><h2>Configured scopes</h2>{scopes.length ? <table><thead><tr><th>Scope</th><th>Source</th><th></th></tr></thead><tbody>{scopes.map((scope) => <tr key={scope.id}><td>{scope.label}<br /><small>{scope.scope_type}</small></td><td>{scope.source_ids.join(", ")}</td><td><button onClick={() => sync(scope.id)}>Sync now</button></td></tr>)}</tbody></table> : <p className="empty">No tracked scope has been configured.</p>}</section><section className="card"><h2>Recent synchronization runs</h2>{runs.length ? <table><thead><tr><th>Started</th><th>Status</th><th>Records</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{new Date(run.started_at).toLocaleString()}</td><td>{run.status}</td><td>{run.error_summary ?? Object.entries(run.record_counts ?? {}).map(([key, value]) => `${value} ${key}`).join(", ")}</td></tr>)}</tbody></table> : <p className="empty">Synchronization history will appear here.</p>}</section></div>;
}
