"use client";
import { useState } from "react";

type Scope = { id: string; label: string; scope_type: string; source_ids: string[]; is_active: boolean };
type Option = { id: string; name: string };
type Group = { id: string; name: string; description: string | null; match_mode: "intersection" | "union"; reporting_group_members: { application_user_id: string }[]; reporting_group_scopes: { scope_id: string }[]; reporting_group_wrike_users: { wrike_user_id: string }[] };
type CustomField = { id: string; title: string; field_type: string | null; enabled: boolean };
type Props = {
  connection: { status: string; account_name: string | null; api_host: string | null; token_expires_at: string | null; updated_at: string } | null;
  scopes: Scope[]; runs: { id: string; status: string; sync_mode?: string; started_at: string; record_counts: Record<string, number>; error_summary: string | null }[];
  groups: Group[]; appUsers: Option[]; wrikeUsers: Option[]; customFields: CustomField[];
  settings: { timezone: string; reporting_access_enforced: boolean; ask_enabled: boolean };
  audit: { id: string; content: string; created_at: string; user_id: string }[];
};

const selected = (event: React.ChangeEvent<HTMLSelectElement>) => [...event.target.selectedOptions].map((option) => option.value);
export function AdminPanel({ connection, scopes, runs, groups, appUsers, wrikeUsers, customFields, settings, audit }: Props) {
  const [label, setLabel] = useState(""); const [scopeType, setScopeType] = useState("folder"); const [sourceId, setSourceId] = useState("");
  const [sourceOptions, setSourceOptions] = useState<{ id: string; title: string; kind: string }[]>([]);
  const [message, setMessage] = useState(""); const [preview, setPreview] = useState<{ title: string; status: string }[]>([]); const connected = connection?.status === "connected";
  const [groupId, setGroupId] = useState<string>(); const [groupName, setGroupName] = useState(""); const [matchMode, setMatchMode] = useState<"intersection" | "union">("intersection"); const [memberIds, setMemberIds] = useState<string[]>([]); const [groupScopeIds, setGroupScopeIds] = useState<string[]>([]); const [groupUserIds, setGroupUserIds] = useState<string[]>([]);
  const [enabledFields, setEnabledFields] = useState(customFields.filter((field) => field.enabled).map((field) => field.id));
  const [timezone, setTimezone] = useState(settings.timezone); const [accessEnforced, setAccessEnforced] = useState(settings.reporting_access_enforced); const [askEnabled, setAskEnabled] = useState(settings.ask_enabled);
  async function jsonCall(url: string, body?: unknown, method = "POST") { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Request failed."); return payload; }
  const sourceIds = () => scopeType === "account" ? ["account"] : scopeType === "list" ? sourceId.split(/[\s,]+/).map((id) => id.trim()).filter(Boolean) : [sourceId.trim()].filter(Boolean);
  async function browseSources() { try { const response = await fetch(`/api/wrike/sources?q=${encodeURIComponent(sourceId)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setSourceOptions(payload.filter((item: { kind: string }) => item.kind === scopeType)); if (!payload.length) setMessage("No Wrike sources matched that search."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to browse Wrike sources."); } }
  async function previewScope() { try { setMessage(""); const payload = await jsonCall("/api/wrike/preview", { scopeType, sourceIds: sourceIds() }); setPreview(payload.tasks); } catch (error) { setMessage(error instanceof Error ? error.message : "Preview failed."); } }
  async function saveScope() { try { await jsonCall("/api/wrike/scopes", { label, scopeType, sourceIds: sourceIds() }); setMessage("Scope saved. Refresh to configure it or run a sync."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save scope."); } }
  async function sync(scopeId: string, mode: "incremental" | "full") { try { setMessage(`${mode === "full" ? "Full resync" : "Change sync"} is running.`); const payload = await jsonCall("/api/wrike/sync", { scopeIds: [scopeId], mode }); setMessage(`Sync completed: ${payload.tasks} tasks and ${payload.timeEntries} time entries processed.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Sync failed."); } }
  async function health() { try { const response = await fetch("/api/wrike/health"); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setMessage(`Wrike healthy: ${payload.account?.name ?? "account"} via ${payload.apiHost} (${payload.latencyMs} ms).`); } catch (error) { setMessage(error instanceof Error ? error.message : "Health check failed."); } }
  async function saveGroup() { try { await jsonCall("/api/admin/reporting-groups", { id: groupId, name: groupName, matchMode, memberIds, scopeIds: groupScopeIds, wrikeUserIds: groupUserIds }); setMessage("Reporting group saved. Refresh to see it in the list."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save group."); } }
  function editGroup(group: Group) { setGroupId(group.id); setGroupName(group.name); setMatchMode(group.match_mode); setMemberIds(group.reporting_group_members.map((item) => item.application_user_id)); setGroupScopeIds(group.reporting_group_scopes.map((item) => item.scope_id)); setGroupUserIds(group.reporting_group_wrike_users.map((item) => item.wrike_user_id)); }
  async function saveFields() { try { await jsonCall("/api/admin/custom-fields", { customFieldIds: enabledFields }); setMessage("Filterable custom fields saved. Run a full resync to populate values."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save custom fields."); } }
  async function saveSettings() { try { await jsonCall("/api/admin/reporting-settings", { timezone, reportingAccessEnforced: accessEnforced, askEnabled }); setMessage("Reporting settings saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save settings."); } }
  return <div className="admin-stack">
    {message && <p className={/failed|unable|invalid|error|not found/i.test(message) ? "notice error" : "notice"}>{message}</p>}
    <div className="admin-grid"><section className="card"><h2>Wrike connection</h2>{connected ? <><p>Connected to <strong>{connection?.account_name ?? "Wrike"}</strong>.</p><p className="muted">Host: {connection?.api_host ?? "Reconnect required"}<br />Token expires: {connection?.token_expires_at ? new Date(connection.token_expires_at).toLocaleString() : "unknown"}</p><div className="filter-bar"><button onClick={health}>Run health check</button><button className="secondary" onClick={async () => { await fetch("/api/wrike/disconnect", { method: "POST" }); location.reload(); }}>Disconnect</button></div></> : <><p>Connect a read-only Wrike account to synchronize reporting data.</p><a className="button" href="/api/wrike/connect">Connect Wrike</a></>}</section>
      <section className="card"><h2>Reporting controls</h2><label>Organization timezone<input value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><label className="check"><input type="checkbox" checked={accessEnforced} onChange={(event) => setAccessEnforced(event.target.checked)} /> Enforce reporting groups</label><label className="check"><input type="checkbox" checked={askEnabled} onChange={(event) => setAskEnabled(event.target.checked)} /> Enable Ask DevTrack</label><button onClick={saveSettings}>Save controls</button><p className="muted">Configure and test groups before enforcing them.</p></section></div>
    <div className="admin-grid"><section className="card"><h2>Create tracked scope</h2>{!connected ? <p>Connect Wrike first.</p> : <><div className="form-grid"><input placeholder="Scope label" value={label} onChange={(event) => setLabel(event.target.value)} /><select value={scopeType} onChange={(event) => { setScopeType(event.target.value); setSourceOptions([]); }}><option value="account">Account</option><option value="space">Space</option><option value="folder">Folder</option><option value="project">Project</option><option value="task">Parent task</option><option value="list">List of task IDs</option></select>{scopeType !== "account" && <input placeholder={scopeType === "list" ? "Task IDs, separated by commas" : "Wrike source ID or search text"} value={sourceId} onChange={(event) => setSourceId(event.target.value)} />}</div>{["space", "folder", "project"].includes(scopeType) && <div className="filter-bar compact"><button className="secondary" onClick={browseSources}>Browse Wrike</button>{sourceOptions.length > 0 && <select value="" onChange={(event) => { const option = sourceOptions.find((item) => item.id === event.target.value); setSourceId(event.target.value); if (!label && option) setLabel(option.title); }}><option value="">Choose a source…</option>{sourceOptions.map((item) => <option value={item.id} key={`${item.kind}-${item.id}`}>{item.title}</option>)}</select>}</div>}<div className="filter-bar"><button className="secondary" onClick={previewScope} disabled={!sourceIds().length}>Preview tasks</button><button onClick={saveScope} disabled={!label || !sourceIds().length}>Save scope</button></div>{preview.length > 0 && <p className="muted">Preview: {preview.slice(0, 3).map((task) => task.title).join(", ")}</p>}</>}</section>
      <section className="card"><h2>Filterable custom fields</h2>{customFields.length ? <div className="check-list">{customFields.map((field) => <label className="check" key={field.id}><input type="checkbox" checked={enabledFields.includes(field.id)} onChange={(event) => setEnabledFields(event.target.checked ? [...enabledFields, field.id] : enabledFields.filter((id) => id !== field.id))} /> {field.title} <small>{field.field_type}</small></label>)}</div> : <p>Run a sync to discover Wrike custom fields.</p>}<button onClick={saveFields}>Save custom fields</button></section></div>
    <section className="card"><h2>Configured scopes</h2>{scopes.length ? <table><thead><tr><th>Scope</th><th>Source</th><th>Actions</th></tr></thead><tbody>{scopes.map((scope) => <tr key={scope.id}><td>{scope.label}<br /><small>{scope.scope_type}</small></td><td>{scope.source_ids.join(", ")}</td><td><div className="filter-bar compact"><button onClick={() => sync(scope.id, "incremental")}>Sync changes</button><button className="secondary" onClick={() => sync(scope.id, "full")}>Full resync</button></div></td></tr>)}</tbody></table> : <p className="empty">No tracked scope has been configured.</p>}</section>
    <div className="admin-grid"><section className="card"><h2>{groupId ? "Edit" : "Create"} reporting group</h2><div className="stack"><input placeholder="Group name" value={groupName} onChange={(event) => setGroupName(event.target.value)} /><select value={matchMode} onChange={(event) => setMatchMode(event.target.value as "intersection" | "union")}><option value="intersection">Sources AND people</option><option value="union">Sources OR people</option></select><label>App members<select multiple value={memberIds} onChange={(event) => setMemberIds(selected(event))}>{appUsers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Wrike sources<select multiple value={groupScopeIds} onChange={(event) => setGroupScopeIds(selected(event))}>{scopes.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Wrike people<select multiple value={groupUserIds} onChange={(event) => setGroupUserIds(selected(event))}>{wrikeUsers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="filter-bar"><button onClick={saveGroup} disabled={!groupName || (!groupScopeIds.length && !groupUserIds.length)}>Save group</button>{groupId && <button className="secondary" onClick={() => { setGroupId(undefined); setGroupName(""); setMemberIds([]); setGroupScopeIds([]); setGroupUserIds([]); }}>Cancel</button>}</div></div></section>
      <section className="card"><h2>Reporting groups</h2>{groups.length ? <ul className="detail-list">{groups.map((group) => <li key={group.id}><strong>{group.name}</strong> <small>{group.match_mode}</small><br />{group.reporting_group_members.length} members · {group.reporting_group_scopes.length} sources · {group.reporting_group_wrike_users.length} people <button className="link-button" onClick={() => editGroup(group)}>Edit</button><button className="link-button" onClick={async () => { if (confirm(`Delete ${group.name}?`)) { await jsonCall(`/api/admin/reporting-groups/${group.id}`, undefined, "DELETE"); location.reload(); } }}>Delete</button></li>)}</ul> : <p>No reporting groups configured.</p>}</section></div>
    <section className="card"><h2>Recent synchronization runs</h2>{runs.length ? <table><thead><tr><th>Started</th><th>Mode</th><th>Status</th><th>Records / error</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{new Date(run.started_at).toLocaleString()}</td><td>{run.sync_mode ?? "incremental"}</td><td>{run.status}</td><td>{run.error_summary ?? Object.entries(run.record_counts ?? {}).map(([key, value]) => `${value} ${key}`).join(", ")}</td></tr>)}</tbody></table> : <p className="empty">Synchronization history will appear here.</p>}</section>
    <section className="card"><h2>Ask DevTrack audit</h2>{audit.length ? <table><thead><tr><th>Asked</th><th>User</th><th>Question</th></tr></thead><tbody>{audit.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{appUsers.find((user) => user.id === item.user_id)?.name ?? item.user_id}</td><td>{item.content}</td></tr>)}</tbody></table> : <p>No saved questions yet.</p>}</section>
  </div>;
}
