"use client";
import Link from "next/link";
import { useState } from "react";

type Message = { role: "user" | "assistant"; content: string; references?: { id: string; title: string; href: string }[] };
type Conversation = { id: string; title: string; updated_at: string };
export function AskPanel({ enabled, initialConversations }: { enabled: boolean; initialConversations: Conversation[] }) {
  const [conversationId, setConversationId] = useState<string>(); const [conversations, setConversations] = useState(initialConversations); const [messages, setMessages] = useState<Message[]>([]); const [question, setQuestion] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function ask(event: React.FormEvent) { event.preventDefault(); if (!question.trim() || busy) return; const current = question.trim(); setQuestion(""); setMessages((items) => [...items, { role: "user", content: current }]); setBusy(true); setError(""); try { const response = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ conversationId, message: current }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setConversationId(payload.conversationId); setMessages((items) => [...items, { role: "assistant", content: payload.answer, references: payload.references }]); if (!conversationId) setConversations((items) => [{ id: payload.conversationId, title: current.slice(0, 80), updated_at: new Date().toISOString() }, ...items]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to answer that question."); } finally { setBusy(false); } }
  async function openConversation(id: string) { const response = await fetch(`/api/conversations/${id}`); const payload = await response.json(); if (!response.ok) return setError(payload.error); setConversationId(id); setMessages(payload.messages.map((message: { role: "user" | "assistant"; content: string; result_references: Message["references"] }) => ({ role: message.role, content: message.content, references: message.result_references }))); }
  async function removeConversation(id: string) { await fetch(`/api/conversations/${id}`, { method: "DELETE" }); setConversations((items) => items.filter((item) => item.id !== id)); if (conversationId === id) { setConversationId(undefined); setMessages([]); } }
  if (!enabled) return <section className="card empty"><h2>Ask DevTrack is not enabled</h2><p>An administrator can enable it after reporting groups have been tested.</p></section>;
  return <div className="ask-layout"><aside className="card conversation-list"><div className="split-heading"><h2>History</h2><button className="link-button" onClick={() => { setConversationId(undefined); setMessages([]); }}>New</button></div>{conversations.length ? conversations.map((conversation) => <div className="conversation-item" key={conversation.id}><button onClick={() => openConversation(conversation.id)}>{conversation.title}</button><button aria-label="Delete conversation" onClick={() => removeConversation(conversation.id)}>×</button></div>) : <p className="muted">Questions are saved for 90 days.</p>}</aside><section className="card ask-card"><div className="messages">{messages.length ? messages.map((message, index) => <article className={`message ${message.role}`} key={index}><strong>{message.role === "user" ? "You" : "DevTrack"}</strong><p>{message.content}</p>{message.references?.length ? <div className="reference-links">{message.references.map((reference) => <Link href={reference.href} key={reference.id}>{reference.title}</Link>)}</div> : null}</article>) : <div className="ask-intro"><h2>Ask about visible tasks and time</h2><p>Try “How much time last month by person?”, “Count overdue tasks”, or “Compare planned and actual time this quarter.”</p></div>}</div>{error && <p className="notice error">{error}</p>}<form className="ask-form" onSubmit={ask}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={2000} placeholder="Ask a reporting question…" rows={3} /><button disabled={busy || !question.trim()}>{busy ? "Working…" : "Ask"}</button></form></section></div>;
}
